backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    slug: '{{year}}{{month}}{{day}}-{{hour}}{{minute}}{{second}}'
    label: "お知らせ" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "掲載日", name: "date", widget: "date"}
      - label: "分類"
        name: "categories"
        widget: "select"
        options:
          - {label: "トピック", value: "topic"}
          - {label: "イベント", value: "event"}
          - {label: "レポート", value: "report"}
          - {label: "通知", value: "notification"}
      - label: "画像"
        name: "images"
        widget: "list"
        required: false
        fields:
        - {label: 画像キャプション, name: caption, widget: string}
        - {label: URL, name: url, widget: image}
      - label: "ダウンロードファイル"
        name: "dl_files"
        widget: "list"
        required: false
        fields:
        - {label: ファイル名, name: name, widget: string}
        - {label: URL, name: url, widget: file}
      - {label: "内容", name: "body", widget: "markdown", buttons: ["heading-two", "bold", "italic", "link", "bulleted-list", "numbered-list"]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: タイトル, name: title, widget: string}
          - {label: カバー画像, name: image, widget: image}
          - {label: メッセージ, name: message, widget: string}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: 概要, name: body, widget: markdown, buttons: ["heading-two", "bold", "italic", "link", "bulleted-list", "numbered-list"]}
          - label: 活動経緯
            name: circumstances
            widget: list
            fields:
              - {label: 件名, name: title, widget: string}
              - {label: 年月, name: date, widget: string}
          - label: 理事
            name: directors
            widget: list
            fields:
              - {label: 名前, name: name, widget: string}
              - {label: 役職, name: position, widget: string}
          - label: 連絡先
            name: contact
            widget: object
            fields:
              - {label: 担当, name: staff, widget: string}
              - {label: 住所, name: address, widget: string}
              - {label: 電話番号, name: phone, widget: string}
              - {label: FAX, name: fax, widget: string}
              - {label: e-mail, name: email, widget: string}
      - file: "site/content/cooperation/_index.md"
        label: "Cooperation Page"
        name: "cooperation"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - label: 会員企業
            name: cooperation_members
            widget: list
            fields:
              - {label: 企業名, name: name, widget: string}
              - {label: バナー, name: banner, widget: image}
              - {label: URL, name: url, widget: string}
